apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: frontend
spec:
  selector:
    app: front
  type: NodePort
  ports:
  - name: http
    port: 4200
    targetPort: 4200
    nodePort: 30800
