apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  strategy: {}
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - image: api-restaurant:v1.0.0
        name: back
        ports:
        - containerPort: 3333
        env:
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: pg_host
        - name: PG_USER
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: pg_user
        - name: PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: pg_password
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: pg_database
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: back-config
              key: pg_port
        resources: {}
status: {}
