apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
  namespace: database
data:
  init.sql: |
    -- Criação da tabela products
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      price DECIMAL NOT NULL,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );

    -- Criação da tabela tables
    CREATE TABLE IF NOT EXISTS tables (
      id SERIAL PRIMARY KEY,
      table_number INTEGER NOT NULL,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );

    -- Criação da tabela tables_sessions
    CREATE TABLE IF NOT EXISTS tables_sessions (
      id SERIAL PRIMARY KEY,
      table_id INTEGER NOT NULL REFERENCES tables(id),
      opened_at TIMESTAMP DEFAULT NOW(),
      closed_at TIMESTAMP
    );

    -- Criação da tabela orders
    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      table_session_id INTEGER NOT NULL REFERENCES tables_sessions(id),
      product_id INTEGER NOT NULL REFERENCES products(id),
      quantity INTEGER NOT NULL,
      price DECIMAL NOT NULL,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );

  insert_products.sql: |
    INSERT INTO products (name, price) VALUES
      ('Nhoque quatro queijos', 45),
      ('Isca de frango', 60),
      ('Tilápia com alcaparras', 100),
      ('Escondidinho de carne', 75),
      ('Porção de batatas fritas', 65),
      ('Executivo de frango grelhado', 40),
      ('Executivo de tilápia grelhada', 39),
      ('Caldo de palmito', 30),
      ('Refrigerante 350ml', 7.5),
      ('Suco de laranja 440ml', 10);
